
name: S3 to CleverTap Data Transfer

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  # Also allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  transfer-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          
      - name: Run transfer script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PREFIX: ${{ secrets.S3_PREFIX }}
          CLEVERTAP_HOST: ${{ secrets.CLEVERTAP_HOST }}
          CLEVERTAP_USER: ${{ secrets.CLEVERTAP_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          chmod +x ./s3-to-clevertap.sh
          ./s3-to-clevertap.sh
